### ISSUE TITLE
Effects required for integration

### ISSUE THREAD

**Issue by WhimsySpoon** [hyperb1iss/signalrgb-homeassistant#1]
I have installed this integration and it works great, but I have discovered that the following effects need to be installed in SignalRGB for the switch to operate properly in the following modes:

On : "Falling Stars"
Off: "Good night!"

Once these effects are in stalled, the integration in HA Core must be reloaded to update the effects list, otherwise a service call exception will be thrown.

Could these default effects be set as a configuration option?

**Comment by hyperb1iss** [comment]
Yeah, we used Good Night as a way to turn off all effects since there was no API for this until just recently. Try out 0.4.0 which removes these issues.
