### ISSUE TITLE
v0.4.0 install error

### ISSUE THREAD

**Issue by Robbym05** [hyperb1iss/signalrgb-homeassistant#3]
Really appreciate this integration. I am new to HA and I am getting an error when attempting update to v0.4.0.

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

v0.3.0 works as expected if I manually replace the custom components folder.

**Comment by hyperb1iss** [comment]
Just published 0.5.0 which should fix it, give it a try

**Comment by Robbym05** [comment]
v0.6.1 working with beta Signal, THANKS! This is great!
